name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Can it start
      id: can-it-start
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Can it start
        setup-command: npm run build
        command: npm run start
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CAN-IT-START_RESULTS: "${{steps.can-it-start.outputs.result}}"
      with:
        runners: can-it-start
